# Generated by Django 5.0.1 on 2024-01-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('project_id', models.IntegerField()),
                ('add_date', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Call info',
                'verbose_name_plural': 'Calls info',
            },
        ),
        migrations.DeleteModel(
            name='CallInfo',
        ),
    ]
