# Generated by Django 5.0.1 on 2024-01-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_leads_delete_callinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leads',
            new_name='MainLeads',
        ),
        migrations.AlterModelOptions(
            name='mainleads',
            options={},
        ),
    ]
