# Generated by Django 5.0.1 on 2024-01-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogs',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('projectId', models.CharField(blank=True, max_length=100, null=True)),
                ('addDate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Dialogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QualifiedLeads',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('projectId', models.CharField(blank=True, max_length=100, null=True)),
                ('addDate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'QualifiedLeads',
                'managed': False,
            },
        ),
    ]
