# Generated by Django 5.0.1 on 2024-02-07 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_dialogs_qualifiedleads'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDataInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('lead_id', models.IntegerField(null=True)),
                ('lead_name', models.CharField(max_length=255)),
                ('lead_comment', models.TextField(blank=True, null=True)),
                ('lead_post', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_city', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_business', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_homepage', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_emails', models.JSONField(default=list)),
                ('lead_inn', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_kpp', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_created_at', models.CharField(max_length=255, null=True)),
                ('lead_updated_at', models.CharField(max_length=255, null=True)),
                ('lead_deleted_at', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_parent_lead_id', models.IntegerField(blank=True, null=True)),
                ('lead_tags', models.JSONField(default=list)),
                ('lead_phones', models.CharField(max_length=255)),
                ('contact_id', models.IntegerField(null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_comment', models.TextField(blank=True, null=True)),
                ('contact_post', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_city', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_business', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_homepage', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_emails', models.JSONField(default=list)),
                ('contact_inn', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_kpp', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_created_at', models.CharField(max_length=255, null=True)),
                ('contact_updated_at', models.CharField(max_length=255, null=True)),
                ('contact_deleted_at', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_parent_lead_id', models.IntegerField(null=True)),
                ('contact_tags', models.JSONField(default=list)),
                ('contact_address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phones', models.CharField(max_length=255)),
                ('call_id', models.IntegerField(null=True)),
                ('call_phone', models.CharField(max_length=255)),
                ('call_source', models.CharField(max_length=255)),
                ('call_direction', models.CharField(max_length=255)),
                ('call_params', models.JSONField(default=dict)),
                ('call_lead_id', models.IntegerField(null=True)),
                ('call_organization_id', models.IntegerField(null=True)),
                ('call_user_id', models.IntegerField(null=True)),
                ('call_started_at', models.CharField(max_length=255, null=True)),
                ('call_connected_at', models.CharField(max_length=255, null=True)),
                ('call_ended_at', models.CharField(max_length=255, null=True)),
                ('call_reason', models.CharField(max_length=255)),
                ('call_duration', models.IntegerField(null=True)),
                ('call_scenario_id', models.IntegerField(null=True)),
                ('call_result_id', models.IntegerField(null=True)),
                ('call_incoming_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('call_recording_url', models.URLField(blank=True, null=True)),
                ('call_call_type', models.CharField(max_length=255)),
                ('call_region', models.CharField(max_length=255)),
                ('call_local_time', models.CharField(max_length=255)),
                ('call_call_project_id', models.CharField(max_length=255)),
                ('call_call_project_title', models.CharField(max_length=255)),
                ('call_scenario_result_group_id', models.CharField(max_length=255)),
                ('call_scenario_result_group_title', models.CharField(max_length=255)),
                ('call_result_result_id', models.IntegerField(null=True)),
                ('call_result_result_name', models.CharField(max_length=255)),
                ('call_result_comment', models.TextField(null=True)),
                ('save_date', models.DateTimeField(default=datetime.datetime(2024, 2, 7, 14, 17, 41, 597031))),
            ],
        ),
        migrations.DeleteModel(
            name='Dialogs',
        ),
        migrations.DeleteModel(
            name='QualifiedLeads',
        ),
    ]
