# Generated by Django 5.0.1 on 2024-02-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_alter_calldatainfo_save_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_lead_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_organization_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_result_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_result_result_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_scenario_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_user_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='contact_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='contact_parent_lead_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='lead_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='lead_parent_lead_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
