# Generated by Django 5.0.1 on 2024-02-09 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_alter_calldatainfo_contact_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldatainfo',
            name='save_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
