# Generated by Django 5.0.1 on 2024-02-09 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_alter_calldatainfo_save_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldatainfo',
            name='save_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 12, 51, 11, 249286, tzinfo=datetime.timezone.utc)),
        ),
    ]
