# Generated by Django 5.0.1 on 2024-02-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_alter_calldatainfo_save_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldatainfo',
            name='save_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
