# Generated by Django 5.0.1 on 2024-02-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0017_alter_calldatainfo_save_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_call_project_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_call_project_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_call_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_direction',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_lead_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_local_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_organization_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_params',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_reason',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_region',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_result_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_result_result_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_result_result_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_scenario_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_scenario_result_group_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_scenario_result_group_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='call_user_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='contact_emails',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='contact_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='contact_parent_lead_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='contact_phones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='contact_tags',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='lead_emails',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='lead_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='lead_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='lead_phones',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='lead_tags',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='calldatainfo',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
