# Generated by Django 5.0.1 on 2024-02-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0020_alter_calldatainfo_call_result_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
