# Generated by Django 5.0.1 on 2024-04-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0022_userskpi_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('project_title', models.CharField(max_length=255)),
                ('scenario_title', models.CharField(max_length=255)),
            ],
        ),
    ]
