# Generated by Django 5.0.1 on 2024-04-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0023_projectinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
