# Generated by Django 5.0.1 on 2024-04-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0023_projectinfo_squashed_0024_projectinfo_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='project_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
